### ISSUE TITLE
A Record for www

### ISSUE THREAD

**Issue by drakerehfeld** [alexpareto/visualify#3]
There's no A record for ```www.``` on Digital Ocean's dns settings, so http://www.visualify.xyz/ does _not_ work, but visualify.xyz does. 

Since you have access to the DNS panel, can you add this record when you get a chance? :-) Just an A record with a host of www and value of the IP address of the droplet.

**Comment by drakerehfeld** [comment]
@alexpareto 
you might want this changed since recruiters are looking
![bitmoji](https://render.bitstrips.com/v2/cpanel/10161328-136438207_4-s1-v1.png?transparent=1&width=246)

**Comment by alexpareto** [comment]
needed a little bit of Nginx action in there, but www.visualify.xyz now forwards to visualify.xyz. ;)
